name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: gradle/actions/wrapper-validation@v6
      - uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - run: ./gradlew build
      - run: docker build .
